### ISSUE TITLE
jd_wish2

### ISSUE THREAD

**Issue by 879441855** [gys619/Absinthe#18]
金榜年终奖 这个脚本跑的是提示我：当前未设置 ShareCodeConfigName 或 ShareCodeEnvName 环境变量
这个得在哪里配置

**Comment by gys619** [comment]
这个在code.sh里配置

**Comment by 879441855** [comment]
已收到，谢谢您！！
                                                                ----蔡远超

**Comment by 879441855** [comment]
> code.sh
这个要怎么配置呢？

**Comment by 879441855** [comment]
@gys619 code.sh要怎么配置呢
