### ISSUE TITLE
重复太多了，还有很多活动过期的

### ISSUE THREAD

**Issue by shyshyshyyyy** [gys619/Absinthe#21]
能不能删除一些啊

**Comment by gys619** [comment]
感谢提醒，重复的马上删除，过期的我也不常看不知道哪些过期了

**Comment by yimiaodaren** [comment]
jd_speed.js  天天加速，是不是没有这个活动了？

**Comment by c1023** [comment]
> 



> jd_speed.js 天天加速，是不是没有这个活动了？

这好像是极速版的签到提现的600金币加速，好像失效了
