### ISSUE TITLE
开卡有礼脚本总是提示多账号并发报错

### ISSUE THREAD

**Issue by 834277373** [gys619/Absinthe#22]
当前模式: 双线程，多账号并发运行
【Error】：多账号并发报错，请求过快建议适当调整 sleepNum 参数限制速度 
list index out of range
【Error】：多账号并发报错，请求过快建议适当调整 sleepNum 参数限制速度 
list index out of range
【Error】：多账号并发报错，请求过快建议适当调整 sleepNum 参数限制速度 
list index out of range
【Error】：多账号并发报错，请求过快建议适当调整 sleepNum 参数限制速度 
list index out of range

**Comment by gys619** [comment]
你设置并发了吧，不设置并发跑就行

**Comment by gys619** [comment]
那个脚本也是坏的，不用跑了
