### ISSUE TITLE
更新/ql/repo/gys619_jdd失败，请检查网络...

### ISSUE THREAD

**Issue by 21945764** [gys619/Absinthe#29]
## 开始执行... 2022-01-19 23:44:52

开始克隆仓库 https://ghproxy.com/https://github.com/gys619/jdd.git 到 /ql/repo/gys619_jdd

更新/ql/repo/gys619_jdd失败，重新下载全新仓库...

开始克隆仓库 https://ghproxy.com/https://github.com/gys619/jdd.git 到 /ql/repo/gys619_jdd

更新/ql/repo/gys619_jdd失败，请检查网络...

## 执行结束... 2022-01-19 23:45:07  耗时 15 秒

**Comment by gys619** [comment]
ghproxy代理不让用了，换个代理吧https://pd.zwc365.com/用这个，自己在配置文件里改一下就可以

**Comment by zhangsenpei** [comment]
> ghproxy代理不让用了，换个代理吧[https://pd.zwc365.com/用这个，自己在配置文件里改一下就可以](https://pd.zwc365.com/%E7%94%A8%E8%BF%99%E4%B8%AA%EF%BC%8C%E8%87%AA%E5%B7%B1%E5%9C%A8%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E9%87%8C%E6%94%B9%E4%B8%80%E4%B8%8B%E5%B0%B1%E5%8F%AF%E4%BB%A5)

大大，现在是拉JD项目的命令吗，这个项目里面的拉库命令拉不了，
