### ISSUE TITLE
互助是怎么设置的啊

### ISSUE THREAD

**Issue by ctuooo** [gys619/Absinthe#32]
code.sh和task_before都放进进去，code.sh运行也说配置好了，但是脚本运行还是显示没有配置助力码

**Comment by gys619** [comment]
codehe task_before用的哪儿的文件，我仓库的是旧版，不能用

**Comment by gys619** [comment]
需要用互助研究院最新版。或者我刚才更新了那俩文件，你再更新一些就可以了

**Comment by gys619** [comment]
对，你把那俩文件放config文件夹里面，然后设置 task /ql/config/code.sh 定时任务就好了

**Comment by gys619** [comment]
我也没遇到过，你去群里问一下把

**Comment by zhangsenpei** [comment]
> 我也没遇到过，你去群里问一下把

我按您说的操作了，还是没助力

开始获取配置文件


====================共10个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2022-2-3 12:17:41=====================

东东农场的 互助码环境变量 FRUITSHARECODES，共计 0 组互助码，总大小为 0 字节
由于您环境变量(FRUITSHARECODES)里面未提供助力码，故此处运行将会给脚本内置的码进行助力，请知晓！
共10个京东账号

您提供了0个账号的农场助力码


开始【京东账号1】******

由于您第1个京东账号未提供shareCode,将采纳本脚本自带的助力码

"connect EINVAL 0.1.178.7:80 - Local (0.0.0.0:0)"
东东农场 API请求失败，请检查网路重试
第1个京东账号将要助力的好友[""]

是还缺少哪一步吗

**Comment by ctuooo** [comment]
> > 我也没遇到过，你去群里问一下把
> 
> 我按您说的操作了，还是没助力
> 
> 开始获取配置文件
> 
> ====================共10个京东账号Cookie=========
> 
> ==================脚本执行- 北京时间(UTC+8)：2022-2-3 12:17:41=====================
> 
> 东东农场的 互助码环境变量 FRUITSHARECODES，共计 0 组互助码，总大小为 0 字节 由于您环境变量(FRUITSHARECODES)里面未提供助力码，故此处运行将会给脚本内置的码进行助力，请知晓！ 共10个京东账号
> 
> 您提供了0个账号的农场助力码
> 
> 开始【京东账号1】******
> 
> 由于您第1个京东账号未提供shareCode,将采纳本脚本自带的助力码
> 
> "connect EINVAL 0.1.178.7:80 - Local (0.0.0.0:0)" 东东农场 API请求失败，请检查网路重试 第1个京东账号将要助力的好友[""]
> 
> 是还缺少哪一步吗

下载互助研究院的两个文件试试，我的搞好了

**Comment by ctuooo** [comment]
> 我也没遇到过，你去群里问一下把

用了互助研究院的，配置好了，谢谢大佬了

**Comment by zhangsenpei** [comment]
> > 我也没遇到过，你去群里问一下把
> 
> 用了互助研究院的，配置好了，谢谢大佬了

弱弱问一下，互助研究院去哪里找

**Comment by ctuooo** [comment]
> > > 我也没遇到过，你去群里问一下把
> > 
> > 
> > 用了互助研究院的，配置好了，谢谢大佬了
> 
> 弱弱问一下，互助研究院去哪里找

https://t.me/s/update_help

**Comment by ctuooo** [comment]
> > > 我也没遇到过，你去群里问一下把
> > 
> > 
> > 用了互助研究院的，配置好了，谢谢大佬了
> 
> 弱弱问一下，互助研究院去哪里找

https://share.weiyun.com/yJSWRDCO

**Comment by gys619** [comment]
https://t.me/update_help_group
