### ISSUE TITLE
拉去失败

### ISSUE THREAD

**Issue by lukemin** [gys619/Absinthe#37]
## 开始执行... 2022-02-10 11:24:34

开始更新仓库：/ql/repo/gys619_Absinthe_main

Fetching origin

更新/ql/repo/gys619_Absinthe_main失败，重新下载全新仓库...

开始克隆仓库 https://pd.zwc365.com/https://github.com/gys619/Absinthe.git 到 /ql/repo/gys619_Absinthe_main

更新/ql/repo/gys619_Absinthe_main失败，请检查网络..

**Comment by gys619** [comment]
那个代理坏了，去群里回复拉库就有了
