### ISSUE TITLE
sendNotify.js更新成最新的吧 每次推送都会带一个青龙网址

### ISSUE THREAD

**Issue by QQMate** [gys619/Absinthe#40]
https://github.com/ccwav/QLScript2
这个库的推送文件网址那里是可以用变量设置的，非常方便

**Comment by gys619** [comment]
我就是用的这个的啊，是你没设置变量吧

**Comment by QQMate** [comment]
> 我就是用的这个的啊，是你没设置变量吧

……怎么设置的，我每次更新都会变成系统默认的😂，很难受，我都是再手动复制过去，一份文件

**Comment by gys619** [comment]
你怕不怕复制了我仓库的config.sh ……
有个模板文件jd_config_sample.sh

**Comment by QQMate** [comment]
> 你怕不怕复制了我仓库的config.sh …… 有个模板文件jd_config_sample.sh

还是不行，每次拉库以后青龙都会生成一个默认的sendNotify.js文件，不知道在哪里设置的，repo 文件夹里就是对的，到scripts文件夹就变成默认的了

**Comment by gys619** [comment]
那是青龙问题了，有人说改deps 文件夹内的通知文件可以，你试试

**Comment by niangao0813** [comment]
> > 你怕不怕复制了我仓库的config.sh …… 有个模板文件jd_config_sample.sh
> 
> 还是不行，每次拉库以后青龙都会生成一个默认的sendNotify.js文件，不知道在哪里设置的，repo 文件夹里就是对的，到scripts文件夹就变成默认的了

我也是这个问题 请问解决了吗？

**Comment by gys619** [comment]
README写了
