### ISSUE TITLE
怎么设置不拉取这个文件jdCookie.js每次都会把我的cookie清空

### ISSUE THREAD

**Issue by zeh521** [gys619/Absinthe#52]
怎么设置不拉取这个文件jdCookie.js每次都会把我的cookie清空
很烦

**Comment by gys619** [comment]
cookie在db里，拉那文件怎么会清空呢？
把jdCookie放黑名单那里就行，第二个引号里

**Comment by zeh521** [comment]
> cookie在db里，拉那文件怎么会清空呢？ 把jdCookie放黑那里就行了，第二个引号里

用的最新版青龙面板发现在环境变量里添加cookie没用，不知道怎么解决
