### ISSUE TITLE
大佬改了代理还是拉库失败 为什么呢

### ISSUE THREAD

**Issue by Block2B** [gys619/Absinthe#53]
## 开始执行... 2022-03-11 14:29:35

开始克隆仓库 https://pd.zwc365.com/https://github.com/gys619/jdd.git 到 /ql/repo/gys619_jdd

更新/ql/repo/gys619_jdd失败，重新下载全新仓库...

开始克隆仓库 https://pd.zwc365.com/https://github.com/gys619/jdd.git 到 /ql/repo/gys619_jdd

更新/ql/repo/gys619_jdd失败，请检查网络...

## 执行结束... 2022-03-11 14:29:46  耗时 11 秒

**Comment by gys619** [comment]
那个代理不能用了，去tg 群里找一个
