### ISSUE TITLE
换了各种代理都拉不了库，是哪里错了吗

### ISSUE THREAD

**Issue by ctuooo** [gys619/Absinthe#54]
原来都不用代理裸拉的。

**Comment by gys619** [comment]
@ctuooo 拉库命令👇

原库地址: ql repo https://github.com/gys619/Absinthe.git "jd_|jx_|jddj_|gua_|getJDCookie|wskey" "activity|backUp" "^jd[^_]|USER|utils|ZooFaker_Necklace|JDJRValidator_|sign_graphics_validate|jddj_cookie|function|ql|magic|JDJR|JD|sendNotify" "main"

镜像源①: ql repo https://gh.fakev.cn/gys619/Absinthe.git "jd_|jx_|jddj_|gua_|getJDCookie|wskey" "activity|backUp" "^jd[^_]|USER|utils|ZooFaker_Necklace|JDJRValidator_|sign_graphics_validate|jddj_cookie|function|ql|magic|JDJR|JD|sendNotify" "main"

镜像源②: ql repo https://hub.fastgit.xyz/gys619/Absinthe.git "jd_|jx_|jddj_|gua_|getJDCookie|wskey" "activity|backUp" "^jd[^_]|USER|utils|ZooFaker_Necklace|JDJRValidator_|sign_graphics_validate|jddj_cookie|function|ql|magic|JDJR|JD|sendNotify "main"

配置代理源: ql repo https://dawn-frog-3bbe.1483162508.workers.dev/https://github.com/gys619/Absinthe.git "jd_|jx_|jddj_|gua_|getJDCookie|wskey" "activity|backUp" "^jd[^_]|USER|utils|ZooFakerNecklace|JDJRValidator|sign_graphics_validate|jddj_cookie|function|ql|magic|JDJR|JD|sendNotify" "main"

拉库命令👆

注意:拉不到原库的可以使用镜像源或者使用配置代理源拉

**Comment by ctuooo** [comment]
> @ctuooo 拉库命令👇
> 
> 原库地址: ql repo https://github.com/gys619/Absinthe.git "jd_|jx_|jddj_|gua_|getJDCookie|wskey" "activity|backUp" "^jd[^_]|USER|utils|ZooFaker_Necklace|JDJRValidator_|sign_graphics_validate|jddj_cookie|function|ql|magic|JDJR|JD|sendNotify" "main"
> 
> 镜像源①: ql repo https://gh.fakev.cn/gys619/Absinthe.git "jd_|jx_|jddj_|gua_|getJDCookie|wskey" "activity|backUp" "^jd[^_]|USER|utils|ZooFaker_Necklace|JDJRValidator_|sign_graphics_validate|jddj_cookie|function|ql|magic|JDJR|JD|sendNotify" "main"
> 
> 镜像源②: ql repo https://hub.fastgit.xyz/gys619/Absinthe.git "jd_|jx_|jddj_|gua_|getJDCookie|wskey" "activity|backUp" "^jd[^_]|USER|utils|ZooFaker_Necklace|JDJRValidator_|sign_graphics_validate|jddj_cookie|function|ql|magic|JDJR|JD|sendNotify "main"
> 
> 配置代理源: ql repo https://dawn-frog-3bbe.1483162508.workers.dev/https://github.com/gys619/Absinthe.git "jd_|jx_|jddj_|gua_|getJDCookie|wskey" "activity|backUp" "^jd[^_]|USER|utils|ZooFakerNecklace|JDJRValidator|sign_graphics_validate|jddj_cookie|function|ql|magic|JDJR|JD|sendNotify" "main"
> 
> 拉库命令👆
> 
> 注意:拉不到原库的可以使用镜像源或者使用配置代理源拉

已经拉上了，谢谢，青龙2.11.3拉不上，换个版本就拉上了

**Comment by gys619** [comment]
@ctuooo 那就用旧版本😂
