### ISSUE TITLE
jd_ckck3.sh问题

### ISSUE THREAD

**Issue by azxcvjj** [gys619/Absinthe#55]
wskey只识别了第一个，后面的都说失效然后给禁用了

## 开始执行... 2022-03-24 10:35:49

📑 当前版本：Build 20220323-001-Alpha

📑 开始检查账号有效性 ...

————————————————————————————————————————————
🧑‍🌾【1】**
✅ JD_COOKIE正常
✅ JD_WSCK(wskey)正常
✅ JD_COOKIE -> 更新成功(补全JD_COOKIE备注时间戳)
————————————————————————————————————————————

————————————————————————————————————————————
🧑‍🌾【2】**
✅ JD_COOKIE正常
🚫 JD_WSCK(wskey)失效
🉑 JD_WSCK禁用

✅ JD_COOKIE -> 更新成功(补全JD_COOKIE备注时间戳)
————————————————————————————————————————————

————————————————————————————————————————————
🧑‍🌾【3】**
✅ JD_COOKIE正常
🚫 JD_WSCK(wskey)失效
✅ JD_COOKIE -> 更新成功(补全JD_COOKIE备注时间戳)
————————————————————————————————————————————

————————————————————————————————————————————
🧑‍🌾【4】**
✅ JD_COOKIE正常
🚫 JD_WSCK(wskey)失效
✅ JD_COOKIE -> 更新成功(补全JD_COOKIE备注时间戳)
————————————————————————————————————————————

📊 正在整理通知内容，请耐心等待 ...

💫💫✨JD_WSCK(wskey)失效的账号(共3个)✨💫💫
【2】**
【3】**
【4】**

💫💫✨正常账号(共4个)✨💫💫
【1】**
【2】**
【3】**
【4】**

## 执行结束... 2022-03-24 10:36:05 耗时 16 秒

**Comment by kangwenhang** [comment]
@azxcvjj 那就是失效了

**Comment by azxcvjj** [comment]
> @azxcvjj 那就是失效了

我肯定看过有没有失效呀，我已经确认过第三个肯定是没有失效的，重新抓包看的

**Comment by gys619** [comment]
wskey 脚本呢，有没有写过期，ckck3是互助研究院的😂

**Comment by azxcvjj** [comment]
> wskey 脚本呢，有没有写过期，ckck3是互助研究院的😂

wskey脚本正常的，今天拉下来第一次运行报这样的，我又wskey运行了下正常了，然后又ckck3还是这样

**Comment by gys619** [comment]
@azxcvjj 把ckck3禁用了吧
