### ISSUE TITLE
互助码脚本问题

### ISSUE THREAD

**Issue by knight-666** [gys619/Absinthe#57]
cat: /ql/db/env.db: No such file or directory
cat: /ql/db/env.db: No such file or directory
cat: /ql/db/env.db: No such file or directory
cat: /ql/db/env.db: No such file or directory
cat: /ql/db/env.db: No such file or directory
cat: /ql/db/env.db: No such file or directory
cat: /ql/db/env.db: No such file or directory
cat: /ql/db/env.db: No such file or directory
cat: /ql/db/env.db: No such file or directory

#【01:00:00】 当前 code.sh 的线程数量：6

这个互助码 code.sh 运行后一直不结束，一直都是运行中状态，是不是配置错了啥的

![image](https://user-images.githubusercontent.com/28332512/159887007-0f27e072-39b2-49e9-868e-ed5438e6ea7f.png)

**Comment by kangwenhang** [comment]
@knight-666 env.db怎么没了

**Comment by knight-666** [comment]
> @knight-666 env.db怎么没了

我也不知道，拉下来就没有

**Comment by kangwenhang** [comment]
@knight-666 这个是青龙的，不是脚本里的

**Comment by knight-666** [comment]
> @knight-666 这个是青龙的，不是脚本里的
/ql/db/ 这个目录下有个 database.sqlite  SQLit的数据库

**Comment by knight-666** [comment]
> @knight-666 这个是青龙的，不是脚本里的
![image](https://user-images.githubusercontent.com/28332512/159888717-8cd4bd41-afe3-4082-8dda-84dfc5f6ae3e.png)

**Comment by kangwenhang** [comment]
> > @knight-666 这个是青龙的，不是脚本里的
> ![image](https://user-images.githubusercontent.com/28332512/159888717-8cd4bd41-afe3-4082-8dda-84dfc5f6ae3e.png)
> 
> 

![Screenshot_2022-03-24-17-50-10-217_cn.unas.ufile.jpg](https://user-images.githubusercontent.com/73999482/159890387-a0836d80-099f-4636-846f-9377d23df0cd.jpg)

**Comment by knight-666** [comment]
是不是青龙版本更新了就没有了，我的是 v2.11.3

**Comment by gys619** [comment]
新版就没有了

**Comment by daleyjh** [comment]
我用的v2.12，我写了个解决方案，可以按步骤试试：https://github.com/gys619/Absinthe/issues/82#issue-1260692199
