### ISSUE TITLE
禁用重复任务的脚本问题

### ISSUE THREAD

**Issue by xdfx1180** [gys619/Absinthe#58]
![IMG_20220329_201019](https://user-images.githubusercontent.com/45113856/160608749-8fb984af-7aab-442a-b9cf-0fffba432306.jpg)

**Comment by kangwenhang** [comment]
@xdfx1180 青龙12的脚本位置改了

**Comment by aaahuang** [comment]
遇到了同样的情况，请问有新的脚本吗？

**Comment by SharpX2016** [comment]
同样问题，日志删除周期过大，设置完后再修改数值提示成功，但是一刷新就还原，重启面板就会挂掉。

**Comment by aaahuang** [comment]
您好！我已收到您的邮件！

**Comment by JoshuaYang96** [comment]
> ![IMG_20220329_201019](https://user-images.githubusercontent.com/45113856/160608749-8fb984af-7aab-442a-b9cf-0fffba432306.jpg)

在158行的位置，把路径改为 "/ql/data/config/auth.json"。
with open("/ql/config/auth.json", "r", encoding="utf-8") as f:

**Comment by aaahuang** [comment]
您好！我已收到您的邮件！

**Comment by aaahuang** [comment]
您好！我已收到您的邮件！
