### ISSUE TITLE
code.sh 执行报错

### ISSUE THREAD

**Issue by jrs64** [gys619/Absinthe#76]
有大佬知道这个问题要怎么解决吗
<img width="517" alt="Screen Shot 2022-05-26 at 10 18 12" src="https://user-images.githubusercontent.com/44115045/170401934-c68d3553-8ef5-4147-a968-7479a9a2237c.png">
<img width="508" alt="Screen Shot 2022-05-26 at 10 18 46" src="https://user-images.githubusercontent.com/44115045/170402005-98ca7822-2b08-4d88-888e-5a0e43ce6c00.png">

**Comment by daleyjh** [comment]
我写了个解决方案，可以试一下：https://github.com/gys619/Absinthe/issues/82#issue-1260692199
