### ISSUE TITLE
【解决方案】关于code.sh报错或者不能正常互助的解决方案

### ISSUE THREAD

**Issue by daleyjh** [gys619/Absinthe#82]
由于青龙2.10版本升级后系统崩溃，重装了 2.12版本发现目录变化，并且互助无法执行，研究了半天代码，把我的修复方案列到下面，希望能帮助大家解决2.12版本出现的问题，code.sh修改的步骤如下：
1. 修改repo地址：       `repo9="gys619_Absinthe_main"; repo="$repo9" `
2. 修改数据库文件：     **修改原`$dir_db/env.db` 为 `$dir_db/database.sqlite` (位置在198行)**
3. 添加定时任务：       **添加定时任务：`task code.sh` 任务名称必须这么写,code.sh也不允许改名字，原因：第805-806行代码写死了latest_log和latest_log_path只能读取这个任务名下面的日志，这里代码作者如果还在更新可以调整下自适应。**
                       任务执行间隔1小时更新一次即可，有些环境最后退出时会卡住不动，每次执行会把上次kill掉
4. 放置code.sh：       建议把code.sh放置到config目录，然后链接到scripts目录，而不是直接放置到scripts目录，这样可以方便青龙环境里编辑：`cp 代码库路径/code.sh /ql/data/config/code.sh; ln -s /ql/data/config/code.sh /ql/data/scripts/code.sh `
5. 确认是否生成互助码成功： **互助码最终目录在：/ql/data/log/.ShareCode/; 如：Fruit.log，如果互助码和执行日志里不一样，则检查上面几步是否正确，如果一样了，继续下一步**
6. 代码库里有个mount.sh，执行完以后，把新地址链接到了老地址上，但是这些还不够，可能还会报错，继续第7步挂载
```
#!/usr/bin/env bash
ln -s /ql/data/config /ql/config
ln -s /ql/data/db /ql/db
ln -s /ql/data/jbot /ql/jbot
ln -s /ql/data/log /ql/log
ln -s /ql/data/scripts /ql/scripts
echo "# 旧版青龙目录挂载完成。"
```
7. 挂载其他目录：  
```
ln -s /ql/data/deps /ql/deps;
ln -s /ql/data/repo /ql/repo;  
```
8. 互助码读取：`cp 代码库路径/task_before.sh /ql/data/config/task_before.sh`
执行完毕后，大部分人应该能正常执行了，如果不能，可以自己手工继续看是否还有目录跟老版本不一样

修改后的文件内容，参照我这个文件：
[code.sh.txt](https://github.com/gys619/Absinthe/files/8837340/code.sh.txt)

**Comment by jrs64** [comment]
我刚试了一下，ShareCode文件是有了。但是在执行任务的时候提示没有提供互助码。是哪一步出错了吗
<img width="569" alt="Screen Shot 2022-06-07 at 10 35 18" src="https://user-images.githubusercontent.com/44115045/172283542-3ec6e652-f86e-4fc1-92ff-690e5b485324.png">
<img width="503" alt="Screen Shot 2022-06-07 at 10 35 44" src="https://user-images.githubusercontent.com/44115045/172283605-cad93d98-429c-42ea-a22c-478ee2cf585e.png">

**Comment by jrs64** [comment]
> 我刚试了一下，ShareCode文件是有了。但是在执行任务的时候提示没有提供互助码。是哪一步出错了吗 <img alt="Screen Shot 2022-06-07 at 10 35 18" width="569" src="https://user-images.githubusercontent.com/44115045/172283542-3ec6e652-f86e-4fc1-92ff-690e5b485324.png"> <img alt="Screen Shot 2022-06-07 at 10 35 44" width="503" src="https://user-images.githubusercontent.com/44115045/172283605-cad93d98-429c-42ea-a22c-478ee2cf585e.png">
上面没有拿到互助码，是因为task_before的问题
我是参考这个https://gist.github.com/fzls/14f8d1d3ebb2fef64750ad91d268e4f6解决，没有互助码的问题。

**Comment by knight-666** [comment]
请问下，我的青龙自动升级到了2.13.3版本，但是没有你说的这个/ql/data目录，这种情况怎么处理？
