### ISSUE TITLE
sendNotify.js为旧版文件

### ISSUE THREAD

**Issue by NooAcc** [gys619/Absinthe#83]
本地目录下包含的sendNotify.js文件夹只有900+行，手动修改成最新的3000+行之后，wxpusher一对一推送无异常。之后执行拉库脚本后sendNotify.js又变成了之前那个900+行的文件。

**Comment by gys619** [comment]
README写了你看一下吧

**Comment by NooAcc** [comment]
哇，抱歉，之前没注意到那里。谢谢。
