### ISSUE TITLE
重复通知

### ISSUE THREAD

**Issue by longbinzhao** [gys619/Absinthe#84]
京东农场
禁用重复任务

重复通知.如何处理?
另外如何禁用某些脚本的通知?

**Comment by gys619** [comment]
### 如果通知标题在此变量里面存在（&隔开），则用屏蔽不发送通知，继承Ninja。例：export NOTIFY_SKIP_LIST="京东CK检测&京东资产变动"
export NOTIFY_SKIP_LIST=""
