### ISSUE TITLE
互助问题

### ISSUE THREAD

**Issue by J666Z** [gys619/Absinthe#88]
东东农场 领取失败,原因：给您助力的人未达2个 
东东萌宠 领取失败，原因：给您助力的人未达5个亲（前面6个内部互助了，第7个没有）

**Comment by afwfv** [comment]
@J666Z 次数用完了吧

**Comment by zhouzhouShow** [comment]
我也提示这个,次数用完了是啥意思,需要买吗?不是内部互助吗?

**Comment by afwfv** [comment]
@zhouzhouShow 一个号只有5次，后面就没次数了啊

**Comment by zhouzhouShow** [comment]
没有哦,我看了自己的助力次数还是5次,没有被使用,还有多个账号里面的都是次数未被使用

**Comment by J666Z** [comment]
@zhouzhouShow 我也是这样的

**Comment by afwfv** [comment]
@zhouzhouShow IP有可能黑了

**Comment by gys619** [comment]
@zhouzhouShow 这是互助池，报错的。你code里就没多少互助码吧，

**Comment by gys619** [comment]
@zhouzhouShow 你这图，将要助力的就一个互助码，你其他账号互助码呢？

**Comment by zhouzhouShow** [comment]
> @zhouzhouShow你这图，将要预告的码就是一个互助码，你其他账号互助呢？
我弄好了,谢谢大佬

**Comment by J666Z** [comment]
@gys619 哪里去添加互助码，我看推送有CC提示的互助码

**Comment by zhouzhouShow** [comment]
> @gys619 哪里去添加互助码，我看推送有CC提示的互助码

我看源码里面没有做全局变量的,我直接在源码里面改的,里面有个变量可以放助理码,然后助理码可以从fruit_shareCache.json里面拿到本地账号的,源码是把分享码放到了fruit_shareCache.json这个文件里面,然后在存取进行助力的,但是不知道为啥执行没成功,

**Comment by gys619** [comment]
@zhouzhouShow code，群里有文件

**Comment by J666Z** [comment]
@gys619 怎么跑着跑着突然CK变成了一个还添加了一个备注@@什么的，没留截图，看了CK不是原来的

**Comment by J666Z** [comment]
我刚手动跑任务没有呢，看日志是正常的

**Comment by J666Z** [comment]
京东CK检测, 错误!

接口1检测失败，尝试使用接口2....

京东账号1 : X状态正常!

等待2秒.......	


🔔京东CK检测, 结束! 🕛 3.461 秒

cp: cannot stat '/ql/repo/gys619_Absinthe_main/sendNotify.js': No such file or directory
cp: cannot stat '/ql/repo/gys619_Absinthe_main/sendNotify.js': No such file or directory
