### ISSUE TITLE
拉库失败

### ISSUE THREAD

**Issue by leave668** [gys619/Absinthe#89]
检测到有新的定时任务：

gys619_Absinthe_main/jd_sevenDay_info.js

开始尝试自动添加定时任务...

超级无线店铺签到活动信息 -> 添加失败(Validation error, cannot resolve alias "jd")
加载sendNotify，当前版本: 20220523

**Comment by leave668** [comment]
用的新的拉库命令

**Comment by gys619** [comment]
@leave668 这个是没识别脚本里的定时，等会儿我把它删了

**Comment by Zbl1007** [comment]
> 用的新的拉库命令

您好，新的拉库命令能发下吗

**Comment by gys619** [comment]
@Zbl1007 ql repo https://github.com/gys619/Absinthe.git "jd_|jx_|jddj_|gua_|getJDCookie|wskey" "activity|backUp" "^jd[^_]|USER|utils|ZooFaker_Necklace|JDJRValidator_|sign_graphics_validate|jddj_cookie|function|ql|magic|JDJR|JD|sendNotify|depend" "main"
