### ISSUE TITLE
青龙619脚本目录下core.* 多个文件2G以上大小

### ISSUE THREAD

**Issue by leave668** [gys619/Absinthe#90]
青龙619脚本目录下core.* 多个文件2G以上大小，请问这个文件可以删除吗?怎样让没有或者彻底不生成

**Comment by kangwenhang** [comment]
@leave668 https://www.csdn.net/tags/Mtjagg2sNTY4NTctYmxvZwO0O0OO0O0O.html

**Comment by leave668** [comment]
感谢！
